limit the load on trac.sagemath.org

diff --git a/.github/workflows/ci-sage.yml b/.github/workflows/ci-sage.yml
--- a/.github/workflows/ci-sage.yml
+++ b/.github/workflows/ci-sage.yml
@@ -99,8 +99,9 @@ jobs:
 
     - name: Check out SageMath from trac.sagemath.org
       shell: bash {0}
+      # Random sleep and retry to limit the load on trac.sagemath.org
       run: |
-        git init && git remote add trac ${{ env.SAGE_TRAC_GIT }} && git-trac-command/git-trac checkout $SAGE_TICKET
+        git init && git remote add trac ${{ env.SAGE_TRAC_GIT }} && x=1 && while [ $x -le 5 ]; do x=$(( $x + 1 )); sleep $(( $RANDOM % 40 + 1 )); if git-trac-command/git-trac checkout $SAGE_TICKET; then exit 0; fi; done; exit 1
     - uses: actions/download-artifact@v2
       with:
         path: upstream
@@ -189,7 +190,7 @@ jobs:
       - name: Check out SageMath from trac.sagemath.org
         shell: bash {0}
         run: |
-          git init && git remote add trac ${{ env.SAGE_TRAC_GIT }} && git-trac-command/git-trac checkout $SAGE_TICKET
+          git init && git remote add trac ${{ env.SAGE_TRAC_GIT }} && x=1 && while [ $x -le 5 ]; do x=$(( $x + 1 )); sleep $(( $RANDOM % 40 + 1 )); if git-trac-command/git-trac checkout $SAGE_TICKET; then exit 0; fi; done; exit 1
       - uses: actions/download-artifact@v2
         with:
           path: upstream
